// Generated by https://quicktype.io

export interface Product {
    _id:  string;
    name: string;
    size: string;
    price: number;
    qty:   number;
    tags: string[];
    currentPrice :number;
    currentQty:number;
}
