// Generated by https://quicktype.io

export interface Product {
    _id:  string;
    name: string;
    size: Size[];
    tags: string[];
}

export interface Size {
    _id:   string;
    value: string;
    price: number;
    qty:   number;
}
